builders:
  providerBuilder:
    import: "tool/annotations_process.dart"
    builder_factories: [ "providerBuilder" ,"injectorProvider" ]
    build_extensions: { ".dart": [ '.g.dart' ] }
    auto_apply: root_package
    build_to: source

